apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "nginx-app.fullname" . }}-pv
  labels:
    {{- include "nginx-app.labels" . | nindent 4 }}
spec:
  storageClassName: {{ .Values.persistentVolume.storageClassName }}
  capacity:
    storage: {{ .Values.persistentVolume.size }}
  accessModes:
  {{- range .Values.persistentVolume.accessModes }}
    - {{ . }}
  {{- end }}
  hostPath:
    path: {{ .Values.persistentVolume.hostPath.path }}
  persistentVolumeReclaimPolicy: {{ .Values.persistentVolume.reclaimPolicy }}
