apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "nginx-app.fullname" . }}-pvc
  labels:
    {{- include "nginx-app.labels" . | nindent 4 }}
spec:
  storageClassName: {{ .Values.persistentVolume.storageClassName }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistentVolume.size }}
  
  